sprint2
ClevertecFrontendLab/sprint2-kli2m pull request #1
Opened 2023-02-08 14:04 UTC by kli2m

All tests have been successfully completed

2023-02-08 14:09 UTC, kli2m commented
tests are false

2023-02-08 14:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1675866451/slider%20one%20foto%20768px.png)

2023-02-08 14:54 UTC, klichkovskiy requested changes
Сделай верстку без горизонтально скрола!

2023-02-08 14:54 UTC, klichkovskiy commented on src/components/slider/slider.tsx
> +      <Swiper
![image](https://user-images.githubusercontent.com/62481116/217564183-dcc78924-31de-44f4-8fe6-314d2037379c.png)
Это что со свайпером? сделай правильно

2023-02-08 14:54 UTC, klichkovskiy commented on src/components/menu/menu.tsx
> +        <NavLink
![image](https://user-images.githubusercontent.com/62481116/217564422-8ab35d60-5332-4172-8b81-e2db8d2db089.png)
Что с фоном?

2023-02-08 14:54 UTC, klichkovskiy commented on src/components/menu/menu.tsx
> +export const Menu: React.FC = () => {
![image](https://user-images.githubusercontent.com/62481116/217564554-45b04aba-51f3-45b4-91fe-50de011d9545.png)
меню с книгами должно быть свернуто на всех страницах кроме страницы с книгами

2023-02-08 14:54 UTC, klichkovskiy commented on src/components/menu/menu.tsx
> +export const Menu: React.FC = () => {
![image](https://user-images.githubusercontent.com/62481116/217564835-2127c4aa-787d-4d48-af1a-6e12b7ea2a76.png)
Это что? Почему при открытии адаптивного меню и увеличении разрешения происходит это?

2023-02-10 12:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/kli2m/1676032037/slider%20one%20foto%20768px.png)

2023-02-10 12:28 UTC, kli2m commented on src/components/slider/slider.tsx
> +      <Swiper
done

2023-02-10 12:28 UTC, kli2m commented on src/components/menu/menu.tsx
> +        <NavLink
done

2023-02-10 12:29 UTC, kli2m commented on src/components/menu/menu.tsx
> +export const Menu: React.FC = () => {
If you do this, then the tests do not pass

2023-02-10 12:29 UTC, kli2m commented on src/components/menu/menu.tsx
> +export const Menu: React.FC = () => {
Done

2023-02-10 13:33 UTC, klichkovskiy approved these changes
Фон исправь на кнопках в адаптивном меню в 3 спринте уже. А то не дон получается)

2023-02-10 14:17 UTC, kli2m commented
Монитор не отображает всю палитру цветов( - не вижу всех оттенков

2023-02-10 14:17 UTC, merged